language: python
dist: trusty
sudo: required

python:
  - 3.6

install:
  - "sudo apt-get update"
  - "sudo apt-get install libjpeg8-dev zlib1g-dev python3-pytest"
  - "sudo apt-get install libpulse-mainloop-glib0"      # For qtmultimedia
  - "pip3 install pipenv"
  - "pipenv install --dev"
  - curl -s https://api.github.com/repos/FAForever/uid/releases/latest | jq -r '.assets[] | select(.name == "faf-uid") | .browser_download_url' | wget -i - -O ./lib/faf-uid


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - export PYTEST_QT_API=pyqt5
  - pipenv run pytest -xs --cov src --cov-report term-missing

after_success:
  - coveralls
